-- Mô tả:
--      - Liệt kê top khách hàng có số lượng hợp đồng cao nhất.
--      - Có thể thêm điều kiện lọc theo năm, loại hợp đồng.
--    Tác giả: [Tên bạn hoặc nhóm]
--    Ngày tạo: [DD/MM/YYYY]
--    CSDL: QL_BaoHiem
--    Ghi chú:
--      - Kết hợp dữ liệu từ KHACHHANG, HOPDONG và GOIBAOHIM.