CREATE TABLE HOPDONG(
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    MaGoi INT NOT NULL,
    MaNV_TuVan INT,
    MaSoHD VARCHAR(30) UNIQUE,
    NgayKy DATE NOT NULL,
    NgayHieuLuc DATE NOT NULL,
    NgayHetHan DATE NOT NULL,
    TrangThai NVARCHAR(30) CHECK(TrangThai IN (N'Hiệu lực', N'Hết hạn', N'Tạm dừng', N'Huỷ')),
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaGoi) REFERENCES GOIBAOHIEM(MaGoi),
    FOREIGN KEY (MaNV_TuVan) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT CK_HOPDONG_Ngay CHECK (NgayHetHan >= NgayHieuLuc)
);