<<<<<<< HEAD
CREATE TABLE KHUYENMAI(
    MaKM INT IDENTITY(1,1) PRIMARY KEY,
    TenKM NVARCHAR(150) NOT NULL,
    NoiDung NVARCHAR(255),
    GiaTri DECIMAL(10,2) CHECK(GiaTri >= 0),
    DonVi NVARCHAR(10) CHECK(DonVi IN (N'%', N'VND')),
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL,
    CONSTRAINT CK_KHUYENMAI_Ngay CHECK (NgayKT >= NgayBD)
=======
CREATE TABLE KHUYENMAI(
    MaKM INT IDENTITY(1,1) PRIMARY KEY,
    TenKM NVARCHAR(150) NOT NULL,
    NoiDung NVARCHAR(255),
    GiaTri DECIMAL(10,2) CHECK(GiaTri >= 0),
    DonVi NVARCHAR(10) CHECK(DonVi IN (N'%', N'VND')),
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL,
    CONSTRAINT CK_KHUYENMAI_Ngay CHECK (NgayKT >= NgayBD)
>>>>>>> 59c5acf48653319ce8c913c2014f62e09ddfb835
);