<<<<<<< HEAD
CREATE TABLE HOPDONG_KHUYENMAI(
    MaHD INT,
    MaKM INT,
    PRIMARY KEY (MaHD, MaKM),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
=======
CREATE TABLE HOPDONG_KHUYENMAI(
    MaHD INT,
    MaKM INT,
    PRIMARY KEY (MaHD, MaKM),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
>>>>>>> 59c5acf48653319ce8c913c2014f62e09ddfb835
);