CREATE TABLE THANHTOANPHI(
    MaTT INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    NgayTT DATE NOT NULL,
    SoTien DECIMAL(18,2) CHECK(SoTien >= 0),
    MaHT INT NOT NULL,
    MaNV_Thu INT,
    TrangThai NVARCHAR(30) DEFAULT N'Đã nhận',      
    MaGiaoDich VARCHAR(30) UNIQUE,
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaHT) REFERENCES HINHTHUC_THANHTOAN(MaHT),
    FOREIGN KEY (MaNV_Thu) REFERENCES NHANVIEN(MaNV)
);