CREATE TABLE YEUCAUBOITHUONG(
    MaYC INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    NgayYeuCau DATE NOT NULL,
    NgaySuKien DATE NOT NULL,
    LoaiSuKien NVARCHAR(100),                        
    SoTienYC DECIMAL(18,2) CHECK(SoTienYC >= 0),
    MaTT_TrangThai INT NOT NULL,
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaTT_TrangThai) REFERENCES TINHTRANG_YEUCAU(MaTT)
);