<<<<<<< HEAD
CREATE TABLE CHITRABOITHUONG(
    MaCT INT IDENTITY(1,1) PRIMARY KEY,
    MaYC INT NOT NULL,
    NgayChiTra DATE NOT NULL,
    SoTienChi DECIMAL(18,2) CHECK(SoTienChi >= 0),
    HinhThucChi NVARCHAR(100),
    TrangThai NVARCHAR(30) DEFAULT N'Đã chi trả',
    MaNV_Chi INT,
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaYC) REFERENCES YEUCAUBOITHUONG(MaYC),
    FOREIGN KEY (MaNV_Chi) REFERENCES NHANVIEN(MaNV)
=======
CREATE TABLE CHITRABOITHUONG(
    MaCT INT IDENTITY(1,1) PRIMARY KEY,
    MaYC INT NOT NULL,
    NgayChiTra DATE NOT NULL,
    SoTienChi DECIMAL(18,2) CHECK(SoTienChi >= 0),
    HinhThucChi NVARCHAR(100),
    TrangThai NVARCHAR(30) DEFAULT N'Đã chi trả',
    MaNV_Chi INT,
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaYC) REFERENCES YEUCAUBOITHUONG(MaYC),
    FOREIGN KEY (MaNV_Chi) REFERENCES NHANVIEN(MaNV)
>>>>>>> 59c5acf48653319ce8c913c2014f62e09ddfb835
);