CREATE TABLE TAIKHOAN(
    MaTK INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap VARCHAR(100) UNIQUE,
    MatKhauHash VARBINARY(256),
    LoaiTK NVARCHAR(20) CHECK (LoaiTK IN (N'KH', N'NV')),
    MaKH INT,
    MaNV INT,
    NgayTao DATE DEFAULT GETDATE(),
    TrangThai NVARCHAR(20) DEFAULT N'Hoạt động',
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);