<<<<<<< HEAD
CREATE TABLE LICHSU_TRUY_CAP(
    MaLS BIGINT IDENTITY(1,1) PRIMARY KEY,
    MaTK INT NOT NULL,
    ThoiGian DATETIME2 DEFAULT SYSDATETIME(),
    HanhDong NVARCHAR(200),
    MoTa NVARCHAR(255),
    DiaChiIP VARCHAR(50),
    FOREIGN KEY (MaTK) REFERENCES TAIKHOAN(MaTK)
=======
CREATE TABLE LICHSU_TRUY_CAP(
    MaLS BIGINT IDENTITY(1,1) PRIMARY KEY,
    MaTK INT NOT NULL,
    ThoiGian DATETIME2 DEFAULT SYSDATETIME(),
    HanhDong NVARCHAR(200),
    MoTa NVARCHAR(255),
    DiaChiIP VARCHAR(50),
    FOREIGN KEY (MaTK) REFERENCES TAIKHOAN(MaTK)
>>>>>>> 59c5acf48653319ce8c913c2014f62e09ddfb835
);