USE QL_BaoHiem

CREATE TABLE LOAIBAOHIEM(
    MaLoai INT IDENTITY(1,1) PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL UNIQUE,   -- Tên loại bảo hiểm (Y tế, Nhân thọ, Tài sản)
    MoTa NVARCHAR(255)                       -- Mô tả chi tiết về loại bảo hiểm
);

CREATE TABLE HINHTHUC_THANHTOAN(
    MaHT INT IDENTITY(1,1) PRIMARY KEY,
    TenHT NVARCHAR(100) NOT NULL UNIQUE,     -- Tên hình thức: Tiền mặt, Chuyển khoản, Ví điện tử
    MoTa NVARCHAR(255) 
);

CREATE TABLE TINHTRANG_YEUCAU(
    MaTT INT IDENTITY(1,1) PRIMARY KEY,
    TenTT NVARCHAR(100) NOT NULL UNIQUE,
    MoTa NVARCHAR(255)
);

CREATE TABLE PHONGBAN(
    MaPhong INT IDENTITY(1,1) PRIMARY KEY,
    TenPhong NVARCHAR(100) NOT NULL UNIQUE,
    MoTa NVARCHAR(255)
);

CREATE TABLE NHANVIEN(
    MaNV INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(120) NOT NULL,
    GioiTinh NCHAR(3) CHECK(GioiTinh IN (N'Nam', N'Nữ', N'Khác')),
    NgaySinh DATE,
    SDT VARCHAR(20),
    Email VARCHAR(150) UNIQUE,
    DiaChi NVARCHAR(255),
    ChucVu NVARCHAR(100),
    Luong DECIMAL(18,2) CHECK(Luong >= 0),
    MaPhong INT,
    FOREIGN KEY (MaPhong) REFERENCES PHONGBAN(MaPhong)
);

CREATE TABLE KHACHHANG(
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(120) NOT NULL,
    NgaySinh DATE,
    GioiTinh NCHAR(3) CHECK(GioiTinh IN (N'Nam', N'Nữ', N'Khác')),
    CCCD VARCHAR(20) UNIQUE,
    DiaChi NVARCHAR(255),
    SDT VARCHAR(20),
    Email VARCHAR(150) UNIQUE,
    NgheNghiep NVARCHAR(100),
    ThuNhap DECIMAL(18,2) NULL
);

CREATE TABLE GOIBAOHIEM(
    MaGoi INT IDENTITY(1,1) PRIMARY KEY,
    MaLoai INT NOT NULL,
    TenGoi NVARCHAR(150) NOT NULL UNIQUE,
    PhiDinhKy DECIMAL(18,2) CHECK(PhiDinhKy >= 0),      -- Phí khách hàng đóng theo kỳ
    SoTienBaoHiem DECIMAL(18,2) CHECK(SoTienBaoHiem >= 0), -- Giá trị bảo hiểm
    ThoiHanThang INT CHECK(ThoiHanThang > 0),           -- Thời hạn hợp đồng
    DieuKien NVARCHAR(255),                             -- Điều kiện tham gia
    QuyenLoi NVARCHAR(255),                             -- Quyền lợi chính
    FOREIGN KEY (MaLoai) REFERENCES LOAIBAOHIEM(MaLoai)
);

CREATE TABLE HOPDONG(
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    MaGoi INT NOT NULL,
    MaNV_TuVan INT,
    MaSoHD VARCHAR(30) UNIQUE,
    NgayKy DATE NOT NULL,
    NgayHieuLuc DATE NOT NULL,
    NgayHetHan DATE NOT NULL,
    TrangThai NVARCHAR(30) CHECK(TrangThai IN (N'Hiệu lực', N'Hết hạn', N'Tạm dừng', N'Huỷ')),
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaGoi) REFERENCES GOIBAOHIEM(MaGoi),
    FOREIGN KEY (MaNV_TuVan) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT CK_HOPDONG_Ngay CHECK (NgayHetHan >= NgayHieuLuc)
);

CREATE TABLE KHUYENMAI(
    MaKM INT IDENTITY(1,1) PRIMARY KEY,
    TenKM NVARCHAR(150) NOT NULL,
    NoiDung NVARCHAR(255),
    GiaTri DECIMAL(10,2) CHECK(GiaTri >= 0),
    DonVi NVARCHAR(10) CHECK(DonVi IN (N'%', N'VND')),
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL,
    CONSTRAINT CK_KHUYENMAI_Ngay CHECK (NgayKT >= NgayBD)
);

CREATE TABLE HOPDONG_KHUYENMAI(
    MaHD INT,
    MaKM INT,
    PRIMARY KEY (MaHD, MaKM),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
);

CREATE TABLE THANHTOANPHI(
    MaTT INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    NgayTT DATE NOT NULL,
    SoTien DECIMAL(18,2) CHECK(SoTien >= 0),
    MaHT INT NOT NULL,
    MaNV_Thu INT,
    TrangThai NVARCHAR(30) DEFAULT N'Đã nhận',      
    MaGiaoDich VARCHAR(30) UNIQUE,
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaHT) REFERENCES HINHTHUC_THANHTOAN(MaHT),
    FOREIGN KEY (MaNV_Thu) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE YEUCAUBOITHUONG(
    MaYC INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    NgayYeuCau DATE NOT NULL,
    NgaySuKien DATE NOT NULL,
    LoaiSuKien NVARCHAR(100),                        
    SoTienYC DECIMAL(18,2) CHECK(SoTienYC >= 0),
    MaTT_TrangThai INT NOT NULL,
    GhiChu NVARCHAR(255),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
    FOREIGN KEY (MaTT_TrangThai) REFERENCES TINHTRANG_YEUCAU(MaTT)
);

    CREATE TABLE CHITRABOITHUONG(
        MaCT INT IDENTITY(1,1) PRIMARY KEY,
        MaYC INT NOT NULL,
        NgayChiTra DATE NOT NULL,
        SoTienChi DECIMAL(18,2) CHECK(SoTienChi >= 0),
        HinhThucChi NVARCHAR(100),
        TrangThai NVARCHAR(30) DEFAULT N'Đã chi trả',
        MaNV_Chi INT,
        GhiChu NVARCHAR(255),
        FOREIGN KEY (MaYC) REFERENCES YEUCAUBOITHUONG(MaYC),
        FOREIGN KEY (MaNV_Chi) REFERENCES NHANVIEN(MaNV)
    );

CREATE TABLE TAIKHOAN(
    MaTK INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap VARCHAR(100) UNIQUE,
    MatKhauHash VARBINARY(256),
    LoaiTK NVARCHAR(20) CHECK (LoaiTK IN (N'KH', N'NV')),
    MaKH INT,
    MaNV INT,
    NgayTao DATE DEFAULT GETDATE(),
    TrangThai NVARCHAR(20) DEFAULT N'Hoạt động',
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE LICHSU_TRUY_CAP(
    MaLS BIGINT IDENTITY(1,1) PRIMARY KEY,
    MaTK INT NOT NULL,
    ThoiGian DATETIME2 DEFAULT SYSDATETIME(),
    HanhDong NVARCHAR(200),
    MoTa NVARCHAR(255),
    DiaChiIP VARCHAR(50),
    FOREIGN KEY (MaTK) REFERENCES TAIKHOAN(MaTK)
);